wxtemplate:
  templates:
    - {"templateId":"1","templateFilePath":"F:/2021_learn_project/kafka_application_case/src/main/resources/template/template.json","active":true}
    - {"templateId":"2","templateFilePath":"F:/2021_learn_project/kafka_application_case/src/main/resources/template/template.json","active":false}
  template-result-type: 0 # 0-文件获取 1-数据库获取 2-ES
  template-result-file-path: "F:/2021_learn_project/kafka_application_case/src/main/resources/template/templateResult.json"
server:
  port: 9099